name: Deploy Code

on:
  workflow_run:
    workflows: ["Build Code", "Test Code"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    environment:
      name: production

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2

      - name: deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: deploy to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          script: |
            cd app/src
            git pull
            echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart api
